#quarkus.datasource.db-kind=mysql
#quarkus.datasource.username=root
#quarkus.datasource.password=LIMSDB2024
#quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/Scope
#quarkus.datasource.reactive.url=mysql:///Scope
#quarkus.datasource.reactive.max-size=20
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/asd-db
quarkus.datasource.reactive.url=postgresql://localhost:5432/asd-db
quarkus.datasource.reactive.max-size=20
quarkus.http.test-port=9090

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=hkaibni.me
quarkus.log.category."org.jboss.resteasy.reactive".level=DEBUG
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.swagger-ui.always-include=true
quarkus.hibernate-orm.sql-load-script=test-import-psql.sql,user-import-psql.sql,panel-import-psql.sql,media-import-psql.sql
quarkus.http.host=0.0.0.0
quarkus.http.port=8080

