quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=LIMSDB2024
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/Scope
quarkus.datasource.reactive.url=mysql:///Scope
quarkus.datasource.reactive.max-size=20

smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=hkaibni.me
quarkus.log.category."org.jboss.resteasy.reactive".level=DEBUG
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.swagger-ui.always-include=true
quarkus.hibernate-orm.sql-load-script=test-import.sql

